Newhiredoctype.create :name => "Official transcript"
Newhiredoctype.create :name => "Evaluation of non-U.S. documents (if applicable)"
Newhiredoctype.create :name => "Current curriculum vita"
Newhiredoctype.create :name => "Course syllabus"
Newhiredoctype.create :name => "Signed offer letter"